add ubuntu support (#12)

diff --git a/scanner.yml b/scanner.yml
--- a/scanner.yml
+++ b/scanner.yml
@@ -2,7 +2,18 @@
   image: "docker:26.1.0"
 
   before_script:
-    - apk add --no-cache bash curl git openssh-client coreutils
+    - |
+        {
+          source /etc/os-release || true
+          case "${ID:-unknown}" in
+            alpine)
+              apk add --no-cache bash curl git openssh-client coreutils
+              ;;
+            unknown)
+              echo "Unable to detect operating system"
+              ;;
+          esac;
+        }
     - |
         boost_init_config () {
           boost_log_info () {
